services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:5000
    networks:
      - app-network

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge